# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-02 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('Apellido', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
